BackendTestAguilar/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required
from apps.user.views import LoginFormView, HomeView, MenuView


urlpatterns = [
	path('', HomeView.as_view() , name='index'),
	path('menu/<str:uuid>', MenuView.as_view() , name='index'),
	path('login/', LoginFormView.as_view(), name= 'login'),
	path('logout/', login_required(LogoutView.as_view(next_page='login')), name='logout'),
	path('kitchen/', include('apps.kitchen.urls')),
	path('diner/', include('apps.diner.urls')),
	path('employee/', include('apps.user.urls')),
]

apps/kitchen/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.kitchen.views import *

urlpatterns = [
    path('', login_required(KitchenView.as_view()), name='kitchen_view'),
    path('foods', login_required(FoodListView.as_view()), name='food_list_view'),
    path('foods/new-food', login_required(FoodCreateView.as_view()), name='food_create_view'),
    path('foods/delete-food/<int:pk>', login_required(FoodDeleteView.as_view()), name='food_delete_view'),
    path('foods/new-combo', login_required(ComboCreateView.as_view()), name='combo_create_view'),
    path('foods/delete-combo/<int:pk>', login_required(ComboDeleteView.as_view()), name='combo_delete_view'),
    path('menus', login_required(MenuListView.as_view()), name='menu_list_view'),
    path('menus/new-menu', login_required(MenuCreateView.as_view()), name='menu_create_view'),
    path('menus/delete-menu/<int:pk>', login_required(MenuDeleteView.as_view()), name='menu_delete_view'),
]

apps/kitchen/models.py
import uuid
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.
class Ingredient(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return 'Sin {}'.format(self.name)
        
    class Meta:
        db_table = 'ingredient'
        ordering = ['name']

class Food(models.Model):
    name = models.CharField(max_length=50, unique=True)
    type_f = models.CharField(max_length=50)
    exceptions = models.ManyToManyField(Ingredient, blank=True)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        db_table = 'food'
        ordering = ['name']

class Combo(models.Model):    
    name = models.CharField(max_length=50)
    food = models.ManyToManyField(Food)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        db_table = 'combo'
        ordering = ['name']

class Menu(models.Model):
    date = models.DateField(unique=True)
    combo = models.ManyToManyField(Combo)
    uuid = models.UUIDField(null=True, default=uuid.uuid4, editable=False)

    class Meta:
        db_table = 'menu'
        ordering = ['id']
    
class Order(models.Model):
    employee = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(default=datetime.now, verbose_name='Fecha')
    combo = models.ForeignKey(Combo, on_delete=models.CASCADE)
    exceptions = models.ManyToManyField(Ingredient, blank=True)

    class Meta:
        db_table = 'order'
        ordering = ['id']   

apps/kitchen/forms.py
from django import forms
from apps.kitchen.models import Food, Menu, Combo
from datetime import datetime


class DateInput(forms.DateInput):
	input_type = 'date'

class FoodForm(forms.ModelForm):
	class Meta:
		model = Food
		fields = '__all__'
		labels = {
			'name': 'Nombre',
			'exceptions': 'Excepciones'
		}
		widgets = {
			'name': forms.TextInput(attrs={'class':'form-control'}),
			'exceptions': forms.CheckboxSelectMultiple()
		}

class ComboForm(forms.ModelForm):
	class Meta:
		model = Combo
		fields = '__all__'
		labels = {
			'name': 'Nombre',
			'food': 'Comidas'
		}
		widgets = {
			'name': forms.TextInput(attrs={'class':'form-control'}),
			'food': forms.CheckboxSelectMultiple()
		}


class MenuForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(MenuForm, self).__init__(*args, **kwargs)
		self.fields['date'].initial = datetime.now()

	class Meta:
		model = Menu
		fields = '__all__'
		labels = {
			'name': 'Nombre',
    		'date': 'Fecha',
    		'combo': 'Combos',
		}
		widgets = {
			'name': forms.TextInput(attrs={'class':'form-control'}),
			'date': DateInput(attrs={'class':'form-control'}),
			'combo': forms.CheckboxSelectMultiple()  
		}

apps/kitchen/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import ListView, CreateView, DeleteView
from django.contrib.auth.models import User
from datetime import datetime
from apps.kitchen.models import Order, Menu, Food, Combo
from apps.kitchen.forms import MenuForm, FoodForm, ComboForm
from apps.kitchen.tasks import sendSlackMessage

class KitchenView(ListView):
	model = Order
	template_name = 'kitchen.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['timeNow'] = datetime.now 
		return context


class FoodListView(ListView):
	model = Food
	template_name = 'foods/foods.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['combos'] = Combo.objects.all()
		return context

class FoodCreateView(CreateView):
	model = Food
	form_class = FoodForm
	template_name = 'foods/food_create_form.html'
	success_url = reverse_lazy('food_list_view')	 

class FoodDeleteView(DeleteView):
	model = Food
	form_class = FoodForm
	template_name = 'foods/food_delete.html'
	success_url = reverse_lazy('food_list_view')

class ComboCreateView(CreateView):
	model = Combo
	form_class = ComboForm
	template_name = 'foods/combo_create_form.html'
	success_url = reverse_lazy('food_list_view')	 

class ComboDeleteView(DeleteView):
	model = Combo
	form_class = ComboForm
	template_name = 'foods/combo_delete.html'
	success_url = reverse_lazy('food_list_view')

class MenuListView(ListView):
	model = Menu
	template_name = 'menus/menus.html'

class MenuCreateView(CreateView):
	model = Menu
	form_class = MenuForm
	template_name = 'menus/menu_create_form.html'
	success_url = reverse_lazy('menu_list_view')
	
	def form_valid(self, form):
		self.object = form.save()
		sendSlackMessage(self.object.id)
		return super().form_valid(form)

class MenuDeleteView(DeleteView):
	model = Menu
	form_class = MenuForm
	template_name = 'menus/menu_delete.html'
	success_url = reverse_lazy('menu_list_view')

	

apps/kitchen/templates/foods/combo_create_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Nuevo Plato{% endblock title %}

{% block header %}
	<h1 class="container">Crear un nuevo combo</h1>
{% endblock header %}


{% block content %}
    <div class="container">
        <p>Indique los platos que desea para su combo</p>
        <form class="form" method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }} 
            <button type="submit" class="btn btn-sm btn-primary">Guardar</button>
            <a href="/kitchen/foods" class="btn btn-sm btn-danger">Cancelar</a>
        </form>
    </div>
{% endblock content %}

apps/kitchen/templates/foods/combo_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Eliminar Combo{% endblock title %}

{% block header %}
	<h1 class="container">Eliminar un combo</h1>
{% endblock header %}


{% block content %}
    <div class="container">
        <div class="alert alert-danger" role="alert">
            Está seguro de eliminar el combo {{ object.name }}
        </div>
        <form class="form" method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }} 
            <button type="submit" class="btn btn-sm btn-primary">Aceptar</button>
            <a href="/kitchen/foods" class="btn btn-sm btn-danger">Cancelar</a>
        </form>
    </div>
{% endblock content %}

apps/kitchen/templates/foods/food_create_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Nuevo Plato{% endblock title %}

{% block header %}
	<h1 class="container">Agregar un nuevo plato</h1>
{% endblock header %}


{% block content %}
	<div class="container">
		<p>Indique los datos de su nuevo plato</p>
		<form class="form" method="POST" action="">
			{% csrf_token %}
			{% if form.non_field_errors %}
			<div class="alert alert-danger" role="alert">					
				{{ form.non_field_errors }}
			</div>
			{%endif%}
			<div class="form-group">
				<label for="id_name">Nombre</label>                
				{{ form.name }}
				<small id="emailHelp" class="form-text text-muted">Ingrese un nombre no existente.</small>             
				<div class="invalid-feedback">
					{{form.name.errors}}
				</div>
			</div>            
			<div class="form-group">
				<label for="type">Tipo</label>
				<select class="form-control" id="type" name="type_f" required="required">
					<option value="principal">Plato Principal</option>
				  	<option value="ensalada">Ensalada</option>
				  	<option value="postre">Postre</option>
				</select>    
				<div class="invalid-feedback">
					{{form.type_f.errors}}
				</div>
			</div>
			<div class="form-group">
				<label for="id_exceptions">Excepciones</label>  
				<small id="emailHelp" class="form-text text-muted">Indique los ingredientes que el cliente puede eliminar de la comida.</small> 
				<div class="form-check">                
					{{ form.exceptions }}
				</div>    
				<div class="invalid-feedback">
					{{form.exceptions.errors}}
				</div>
			</div>
			<div class="block">
				<button type="submit" class="btn btn-sm btn-primary">Guardar</button>
				<a href="/kitchen/foods" class="btn btn-sm btn-danger">Cancelar</a>
			</div>
		</form>
	</div>
{% endblock content %}

apps/kitchen/templates/foods/food_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Eliminar plato{% endblock title %}

{% block header %}
	<h1 class="container">Eliminar plato</h1>
{% endblock header %}


{% block content %}
    <div class="container">
        <div class="alert alert-danger" role="alert">
            Está seguro de eliminar el plato "{{object.name}}"?
        </div>
        <form class="form" method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }} 
            <button type="submit" class="btn btn-sm btn-primary">Aceptar</button>
            <a href="/kitchen/foods" class="btn btn-sm btn-danger">Cancelar</a>
        </form>
    </div>
{% endblock content %}

apps/kitchen/templates/foods/foods.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Platos{% endblock title %}

{% block header %}
<h1 class="container">Platos</h1>
{% endblock header %}


{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-8">
			<header class="my-4 d-flex justify-content-between align-items-center">
				<h5>Combos</h5>
				<a href="/kitchen/foods/new-combo" 	class="btn btn-primary btn-sm">+</a>
			</header>
			{% if combos %}
			<div class="row">
				{% for combo in combos %}
				<div class="col-md-6">
					<div class="card">
						<div class="card-body">
							<header class="my-4 d-flex justify-content-between align-items-center">
								<h5>{{combo.name}} </h5>	
								<a type="button" class="btn btn-sm btn-danger" href="foods/delete-combo/{{combo.id}}"> x </a>							
							</header>							
							<ul class="list-group">
								{% for food in combo.food.all %}
								<li class="list-group-item">
									<p>
										<span>
											{% if food.type_f == 'ensalada' %}
											<img src="{% static 'imgs/salad.svg' %}" alt="salad" width="40">
											{% elif food.type_f == 'principal' %}
											<img src="{% static 'imgs/principal.svg' %}" alt="principal" width="40">
											{% elif food.type_f == 'postre' %}
											<img src="{% static 'imgs/sweet.svg' %}" alt="sweet" width="40">
											{% else %}
											<img src="{% static 'imgs/none.svg' %}" alt="none" width="40">
											{% endif %}
										</span> 
										{{food.name}}
									</p>
								</li>
								{% endfor %}
							</ul>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
			{% else %}
			<p class="text-center">No hay combos registrados. Si desea puede agregar uno <a href="/kitchen/foods/new-combo">acá</a></p>
			{% endif %}
		</div>
		<div class="col-md-4">
			<header class="my-4 d-flex justify-content-between align-items-center">
				<h5>Platillos</h5>
				<a href="/kitchen/foods/new-food" class="btn btn-primary btn-sm">+</a>
			</header>
			<ul class="list-group">
				{% for food in object_list %}
				<li class="list-group-item  d-flex justify-content-between align-items-center">
					<p>
						<span>
							{% if food.type_f == 'ensalada' %}
							<img src="{% static 'imgs/salad.svg' %}" alt="salad" width="20">
							{% elif food.type_f == 'principal' %}
							<img src="{% static 'imgs/principal.svg' %}" alt="principal" width="20">
							{% elif food.type_f == 'postre' %}
							<img src="{% static 'imgs/sweet.svg' %}" alt="sweet" width="20">
							{% else %}
							<img src="{% static 'imgs/none.svg' %}" alt="none" width="20">
							{% endif %}
						</span> 
						{{food.name}}
					</p>
					<a type="button" class="btn btn-sm btn-danger" href="foods/delete-food/{{food.id}}"> x </a>
				</li>  
				{% endfor %}
			</ul>
		</div>
	</div>
</div>
{% endblock content %}